version: "3"
services:
       fitfriends:
           container_name: fitfriends
           image: latest123/app
           restart: always
           build: .
           ports:
             - "3000:3000"
           environment:
             MONGO_DB_URI: mongodb://natsinee:natsineedev@mongo/test?authSource=admin
           env_file:
             - .env
           links:
             - mongo
          #  mongo-database:
          #   container_name: mongofit
       mongo:
             container_name: mongofit
             image: mongo
             user: 1000:1000
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'
             environment:
              MONGO_INITDB_ROOT_USERNAME: natsinee
              MONGO_INITDB_ROOT_PASSWORD: natsineedev
              MONGO_INITDB_DATABASE: test
             env_file:
             - .env
      
              
